# TypeSpec開発環境用のDocker Compose設定
services:
  # PostgreSQLデータベース
  postgres:
    image: postgres:15-alpine
    container_name: typespec-postgres
    environment:
      POSTGRES_DB: userdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/ddl:/docker-entrypoint-initdb.d
    networks:
      - typespec-network

  # TypeSpec専用環境
  typespec:
    build:
      context: .
      dockerfile: typespec/Dockerfile
    container_name: typespec
    volumes:
      - .:/app    # プロジェクト全体をマウント
      - /app/typespec/node_modules  # node_modules用匿名ボリューム
    working_dir: /app/typespec
    command: /bin/sh -c "while :; do sleep 10; done"
    networks:
      - typespec-network

  # Python Generator専用環境
  generator:
    build:
      context: .
      dockerfile: generator/Dockerfile
    container_name: generator
    volumes:
      - .:/app
    working_dir: /app
    command: /bin/sh -c "while :; do sleep 10; done"
    networks:
      - typespec-network
    depends_on:
      - typespec

  # TypeSpec Web Service
  web-service:
    build:
      context: ./web-service
      dockerfile: Dockerfile
    container_name: typespec-web-service
    ports:
      - "8000:8000"
    volumes:
      - .:/workspace
    environment:
      - WORKSPACE_PATH=/workspace
    networks:
      - typespec-network
    depends_on:
      - typespec
      - generator

  # Spring Boot API（将来的に追加）
  # api:
  #   image: openjdk:11-jre-slim
  #   container_name: typespec-api
  #   volumes:
  #     - ./backend/src:/app
  #   working_dir: /app
  #   ports:
  #     - "8080:8080"
  #   networks:
  #     - typespec-network
  #   depends_on:
  #     - postgres

  # Angular フロントエンド（将来的に追加）
  # frontend:
  #   image: node:18-alpine
  #   container_name: typespec-frontend
  #   volumes:
  #     - ./frontend/src:/app
  #   working_dir: /app
  #   ports:
  #     - "4200:4200"
  #   networks:
  #     - typespec-network

volumes:
  postgres_data:

networks:
  typespec-network:
    driver: bridge