openapi: 3.0.0
info:
  title: Order API
  version: 1.0.0
tags: []
paths:
  /api/v1/order/entry:
    post:
      operationId: post_entry
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
components:
  schemas:
    User:
      type: object
      required:
        - id
        - name
        - email
      properties:
        id:
          type: string
          pattern: ^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$
          description: ユーザーID
        name:
          type: string
          maxLength: 255
          description: ユーザー名
        email:
          type: string
          maxLength: 255
          format: email
          description: メールアドレス
      description: ユーザー情報
